import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Iniciando seed de datos de demostración...\n')

  // Limpiar datos existentes (opcional)
  console.log('🗑️  Limpiando datos existentes...')
  await prisma.invoice.deleteMany()
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()
  await prisma.cartItem.deleteMany()
  await prisma.product.deleteMany()
  await prisma.user.deleteMany()
  console.log('✅ Datos limpiados\n')

  // Crear usuarios de demostración
  console.log('👥 Creando usuarios...')
  const users = await Promise.all([
    prisma.user.create({
      data: {
        email: 'admin@demo.com',
        name: 'Administrador Demo',
        password: '$2b$10$abcdefghijklmnopqrstuvwxyz', // hash fake
        role: 'ADMIN',
        phone: '+51 999 888 777',
        address: 'Av. Javier Prado 123, San Isidro, Lima',
        dni: '12345678',
      },
    }),
    prisma.user.create({
      data: {
        email: 'cliente1@demo.com',
        name: 'Juan Pérez García',
        password: '$2b$10$abcdefghijklmnopqrstuvwxyz',
        role: 'USER',
        phone: '+51 987 654 321',
        address: 'Jr. Los Olivos 456, Miraflores, Lima',
        dni: '87654321',
      },
    }),
    prisma.user.create({
      data: {
        email: 'cliente2@demo.com',
        name: 'María Rodríguez López',
        password: '$2b$10$abcdefghijklmnopqrstuvwxyz',
        role: 'USER',
        phone: '+51 965 432 198',
        address: 'Av. Benavides 789, Surco, Lima',
        dni: '45678912',
      },
    }),
    prisma.user.create({
      data: {
        email: 'empresa@demo.com',
        name: 'Comercial Los Andes SAC',
        password: '$2b$10$abcdefghijklmnopqrstuvwxyz',
        role: 'USER',
        phone: '+51 954 321 876',
        address: 'Av. Industrial 234, Callao',
        ruc: '20123456789',
        businessName: 'Comercial Los Andes SAC',
      },
    }),
  ])
  console.log(`✅ ${users.length} usuarios creados\n`)

  // PRODUCTOS - ROPA (10 productos)
  console.log('👕 Creando productos de ROPA...')
  const ropaProducts = await Promise.all([
    prisma.product.create({
      data: {
        name: 'Polo Nike Deportivo Dri-FIT',
        description: 'Polo deportivo de alta tecnología con tejido Dri-FIT que absorbe el sudor. Perfecto para entrenamientos intensos y actividades al aire libre. Diseño ergonómico y ligero.',
        category: 'ROPA',
        price: 89.90,
        comparePrice: 129.90,
        stock: 50,
        sku: 'POLO-NIKE-001',
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500', 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500'],
        featured: true,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Rojo', 'Azul', 'Negro', 'Blanco'],
        brand: 'Nike',
        material: 'Poliéster 100% Dri-FIT',
        slug: 'polo-nike-deportivo-dri-fit',
        metaTitle: 'Polo Nike Deportivo Dri-FIT - Absorbe el Sudor',
        metaDescription: 'Polo deportivo Nike con tecnología Dri-FIT. Disponible en 4 colores y todas las tallas.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Jean Adidas Originals Slim Fit',
        description: 'Jean de corte slim fit con diseño moderno y cómodo. Fabricado con algodón de alta calidad y elastano para mayor flexibilidad. Perfecto para uso diario.',
        category: 'ROPA',
        price: 159.90,
        comparePrice: 199.90,
        stock: 35,
        sku: 'JEAN-ADIDAS-001',
        images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=500', 'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=500'],
        featured: true,
        sizes: ['28', '30', '32', '34', '36'],
        colors: ['Azul Oscuro', 'Negro', 'Gris'],
        brand: 'Adidas',
        material: 'Algodón 98%, Elastano 2%',
        slug: 'jean-adidas-originals-slim-fit',
        metaTitle: 'Jean Adidas Originals Slim Fit - Estilo y Comodidad',
        metaDescription: 'Jean slim fit Adidas con elastano. Diseño moderno para uso diario.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Casaca Puma Impermeable',
        description: 'Casaca deportiva impermeable ideal para días lluviosos. Capucha ajustable, bolsillos con cierre y forro interior térmico. Protección total contra el clima.',
        category: 'ROPA',
        price: 249.90,
        comparePrice: 329.90,
        stock: 25,
        sku: 'CASACA-PUMA-001',
        images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500', 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500'],
        featured: false,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Negro', 'Azul Marino', 'Verde Militar'],
        brand: 'Puma',
        material: 'Nylon impermeable con forro térmico',
        slug: 'casaca-puma-impermeable',
        metaTitle: 'Casaca Puma Impermeable - Protección Total',
        metaDescription: 'Casaca impermeable Puma con capucha y forro térmico.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Zapatillas New Balance 574 Classic',
        description: 'Zapatillas icónicas New Balance 574 con diseño retro y comodidad moderna. Suela de goma EVA, parte superior de gamuza y malla. Perfectas para uso casual.',
        category: 'ROPA',
        price: 329.90,
        stock: 40,
        sku: 'ZAP-NB-574',
        images: ['https://images.unsplash.com/photo-1539185441755-769473a23570?w=500', 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=500'],
        featured: true,
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['Gris', 'Azul', 'Rojo', 'Negro'],
        brand: 'New Balance',
        material: 'Gamuza y malla con suela EVA',
        slug: 'zapatillas-new-balance-574-classic',
        metaTitle: 'Zapatillas New Balance 574 Classic - Estilo Retro',
        metaDescription: 'Zapatillas New Balance 574 con diseño clásico y comodidad superior.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Polera Under Armour Heatgear',
        description: 'Polera de compresión Under Armour con tecnología HeatGear que mantiene el cuerpo fresco y seco. Ideal para entrenamientos de alta intensidad.',
        category: 'ROPA',
        price: 119.90,
        stock: 45,
        sku: 'POL-UA-HEAT-001',
        images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500'],
        featured: false,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Negro', 'Gris', 'Azul'],
        brand: 'Under Armour',
        material: 'Poliéster 84%, Elastano 16%',
        slug: 'polera-under-armour-heatgear',
        metaTitle: 'Polera Under Armour Heatgear - Compresión',
        metaDescription: 'Polera de compresión Under Armour con tecnología HeatGear.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Short Reebok Training Crossfit',
        description: 'Short deportivo diseñado para Crossfit y entrenamientos funcionales. Tela que no se pega, cintura elástica con cordón ajustable.',
        category: 'ROPA',
        price: 79.90,
        stock: 55,
        sku: 'SHORT-RBK-CF-001',
        images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500'],
        featured: false,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Negro', 'Gris', 'Azul Marino'],
        brand: 'Reebok',
        material: 'Poliéster 100%',
        slug: 'short-reebok-training-crossfit',
        metaTitle: 'Short Reebok Training Crossfit',
        metaDescription: 'Short deportivo Reebok ideal para Crossfit.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Gorra Nike Sportswear',
        description: 'Gorra ajustable de perfil bajo con logo Nike bordado. Perfecta para el día a día o actividades deportivas.',
        category: 'ROPA',
        price: 59.90,
        stock: 70,
        sku: 'GORRA-NIKE-001',
        images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500'],
        featured: false,
        sizes: ['Única'],
        colors: ['Negro', 'Blanco', 'Azul', 'Rojo'],
        brand: 'Nike',
        material: 'Algodón 100%',
        slug: 'gorra-nike-sportswear',
        metaTitle: 'Gorra Nike Sportswear - Estilo Casual',
        metaDescription: 'Gorra Nike ajustable con logo bordado.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Buzo Adidas Essentials Hoodie',
        description: 'Buzo con capucha de diseño clásico Adidas. Interior afelpado suave, bolsillo canguro y cordones ajustables. Comodidad garantizada.',
        category: 'ROPA',
        price: 189.90,
        comparePrice: 249.90,
        stock: 30,
        sku: 'BUZO-ADI-ESS-001',
        images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500'],
        featured: false,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Negro', 'Gris', 'Azul Marino'],
        brand: 'Adidas',
        material: 'Algodón 70%, Poliéster 30%',
        slug: 'buzo-adidas-essentials-hoodie',
        metaTitle: 'Buzo Adidas Essentials Hoodie',
        metaDescription: 'Buzo con capucha Adidas de algodón suave.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Medias Puma Performance Pack x6',
        description: 'Pack de 6 pares de medias deportivas Puma. Tecnología anti-olor, arco de soporte y acolchado en puntos clave.',
        category: 'ROPA',
        price: 49.90,
        stock: 80,
        sku: 'MEDIAS-PUMA-6PK',
        images: ['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=500'],
        featured: false,
        sizes: ['S (35-38)', 'M (39-42)', 'L (43-46)'],
        colors: ['Multicolor', 'Negro', 'Blanco'],
        brand: 'Puma',
        material: 'Algodón 75%, Poliéster 20%, Elastano 5%',
        slug: 'medias-puma-performance-pack-x6',
        metaTitle: 'Medias Puma Performance Pack x6',
        metaDescription: 'Pack de 6 pares de medias deportivas Puma.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Pantalón Jogger Nike Tech Fleece',
        description: 'Pantalón jogger con tecnología Tech Fleece que proporciona calidez sin peso extra. Bolsillos con cierre, cintura elástica y puños ajustados.',
        category: 'ROPA',
        price: 279.90,
        comparePrice: 349.90,
        stock: 28,
        sku: 'PANT-NIKE-TF-001',
        images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500'],
        featured: true,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Negro', 'Gris', 'Azul Marino'],
        brand: 'Nike',
        material: 'Tech Fleece (Algodón y Poliéster)',
        slug: 'pantalon-jogger-nike-tech-fleece',
        metaTitle: 'Pantalón Jogger Nike Tech Fleece',
        metaDescription: 'Jogger Nike con Tech Fleece, calidez sin peso.',
      },
    }),
  ])
  console.log(`✅ ${ropaProducts.length} productos de ROPA creados\n`)

  // PRODUCTOS - ELECTRÓNICA (10 productos)
  console.log('💻 Creando productos de ELECTRÓNICA...')
  const electronicaProducts = await Promise.all([
    prisma.product.create({
      data: {
        name: 'Laptop HP Pavilion 15.6" Intel Core i7',
        description: 'Laptop HP con procesador Intel Core i7 de 11va generación, 16GB RAM DDR4, SSD 512GB NVMe, pantalla Full HD IPS, tarjeta gráfica Intel Iris Xe. Perfecta para trabajo y entretenimiento.',
        category: 'ELECTRONICA',
        price: 3299.90,
        comparePrice: 3999.90,
        stock: 15,
        sku: 'LAPTOP-HP-PAV-I7',
        images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500', 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=500'],
        featured: true,
        brand: 'HP',
        warranty: '12 meses',
        specifications: {
          procesador: 'Intel Core i7-1165G7',
          ram: '16GB DDR4',
          almacenamiento: '512GB SSD NVMe',
          pantalla: '15.6" Full HD IPS',
          graficos: 'Intel Iris Xe',
          sistemaOperativo: 'Windows 11 Home',
        },
        slug: 'laptop-hp-pavilion-156-intel-core-i7',
        metaTitle: 'Laptop HP Pavilion 15.6" Core i7 16GB RAM',
        metaDescription: 'Laptop HP con Intel Core i7, 16GB RAM, 512GB SSD. Perfecta para trabajo y multimedia.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'iPhone 15 Pro Max 256GB',
        description: 'iPhone 15 Pro Max con chip A17 Pro, sistema de cámaras Pro avanzado, pantalla Super Retina XDR de 6.7", marco de titanio y USB-C.',
        category: 'ELECTRONICA',
        price: 6499.90,
        stock: 8,
        sku: 'IPHONE-15-PM-256',
        images: ['https://images.unsplash.com/photo-1592286927505-2fd183561c5e?w=500', 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=500'],
        featured: true,
        brand: 'Apple',
        warranty: '12 meses',
        specifications: {
          chip: 'A17 Pro',
          almacenamiento: '256GB',
          pantalla: '6.7" Super Retina XDR',
          camaras: 'Sistema Pro de 48MP',
          bateria: 'Hasta 29 horas de video',
        },
        colors: ['Titanio Natural', 'Titanio Azul', 'Titanio Blanco', 'Titanio Negro'],
        slug: 'iphone-15-pro-max-256gb',
        metaTitle: 'iPhone 15 Pro Max 256GB - Chip A17 Pro',
        metaDescription: 'iPhone 15 Pro Max con A17 Pro, cámara de 48MP y marco de titanio.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Samsung Galaxy S24 Ultra 512GB',
        description: 'Samsung Galaxy S24 Ultra con S Pen integrado, cámara de 200MP, pantalla Dynamic AMOLED 2X de 6.8", procesador Snapdragon 8 Gen 3 y 12GB RAM.',
        category: 'ELECTRONICA',
        price: 5899.90,
        stock: 10,
        sku: 'SAMS-S24U-512',
        images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500'],
        featured: true,
        brand: 'Samsung',
        warranty: '12 meses',
        specifications: {
          procesador: 'Snapdragon 8 Gen 3',
          ram: '12GB',
          almacenamiento: '512GB',
          pantalla: '6.8" Dynamic AMOLED 2X',
          camara: '200MP principal',
          sPen: 'Incluido',
        },
        colors: ['Negro Titanio', 'Gris Titanio', 'Violeta'],
        slug: 'samsung-galaxy-s24-ultra-512gb',
        metaTitle: 'Samsung Galaxy S24 Ultra 512GB con S Pen',
        metaDescription: 'Galaxy S24 Ultra con cámara de 200MP y S Pen integrado.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'AirPods Pro 2da Generación USB-C',
        description: 'AirPods Pro con cancelación activa de ruido, modo de sonido ambiente adaptable, audio espacial personalizado y estuche MagSafe con USB-C.',
        category: 'ELECTRONICA',
        price: 1099.90,
        stock: 25,
        sku: 'AIRPODS-PRO-2-C',
        images: ['https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=500'],
        featured: false,
        brand: 'Apple',
        warranty: '12 meses',
        specifications: {
          cancelacionRuido: 'Activa hasta 2x mejor',
          bateria: 'Hasta 6 horas de audio',
          estuche: 'MagSafe con USB-C',
          resistencia: 'IPX4',
        },
        slug: 'airpods-pro-2da-generacion-usb-c',
        metaTitle: 'AirPods Pro 2 con USB-C - Cancelación de Ruido',
        metaDescription: 'AirPods Pro 2 con cancelación activa de ruido y estuche MagSafe USB-C.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Sony PlayStation 5 Slim 1TB',
        description: 'PlayStation 5 Slim con 1TB de almacenamiento, diseño 30% más compacto, compatibilidad con todos los juegos PS5 y lector de discos Ultra HD Blu-ray.',
        category: 'ELECTRONICA',
        price: 2799.90,
        stock: 12,
        sku: 'PS5-SLIM-1TB',
        images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=500'],
        featured: true,
        brand: 'Sony',
        warranty: '12 meses',
        specifications: {
          almacenamiento: '1TB SSD',
          resolucion: 'Hasta 4K 120Hz',
          rayTracing: 'Sí',
          controlador: 'DualSense incluido',
          lectorDiscos: 'Ultra HD Blu-ray',
        },
        slug: 'sony-playstation-5-slim-1tb',
        metaTitle: 'PlayStation 5 Slim 1TB - Diseño Compacto',
        metaDescription: 'PS5 Slim con 1TB, lector de discos y DualSense incluido.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'MacBook Air M3 13" 16GB 512GB',
        description: 'MacBook Air con chip M3, pantalla Liquid Retina de 13.6", 16GB de memoria unificada, SSD de 512GB y batería de hasta 18 horas.',
        category: 'ELECTRONICA',
        price: 6299.90,
        stock: 7,
        sku: 'MACBOOK-AIR-M3',
        images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500'],
        featured: true,
        brand: 'Apple',
        warranty: '12 meses',
        specifications: {
          chip: 'Apple M3 (8 núcleos CPU, 10 núcleos GPU)',
          ram: '16GB unificada',
          almacenamiento: '512GB SSD',
          pantalla: '13.6" Liquid Retina',
          bateria: 'Hasta 18 horas',
          peso: '1.24 kg',
        },
        colors: ['Gris Espacial', 'Plata', 'Medianoche', 'Luz Estelar'],
        slug: 'macbook-air-m3-13-16gb-512gb',
        metaTitle: 'MacBook Air M3 13" 16GB RAM 512GB SSD',
        metaDescription: 'MacBook Air con chip M3, 18 horas de batería y diseño ultradelgado.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Monitor LG UltraGear 27" 4K 144Hz',
        description: 'Monitor gaming LG UltraGear de 27 pulgadas, resolución 4K, tasa de refresco de 144Hz, tiempo de respuesta 1ms, HDR10, compatibilidad G-Sync y FreeSync.',
        category: 'ELECTRONICA',
        price: 2199.90,
        stock: 18,
        sku: 'MONITOR-LG-27-4K',
        images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500'],
        featured: false,
        brand: 'LG',
        warranty: '24 meses',
        specifications: {
          tamaño: '27 pulgadas',
          resolucion: '3840 x 2160 (4K UHD)',
          refresh: '144Hz',
          tiempoRespuesta: '1ms',
          hdr: 'HDR10',
          sincronizacion: 'G-Sync y FreeSync Premium',
        },
        slug: 'monitor-lg-ultragear-27-4k-144hz',
        metaTitle: 'Monitor LG UltraGear 27" 4K 144Hz Gaming',
        metaDescription: 'Monitor gaming 4K con 144Hz, 1ms y compatibilidad G-Sync/FreeSync.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Teclado Mecánico Logitech G Pro X',
        description: 'Teclado mecánico para gaming Logitech G Pro X con switches intercambiables GX, iluminación RGB LIGHTSYNC, diseño tenkeyless compacto.',
        category: 'ELECTRONICA',
        price: 599.90,
        stock: 30,
        sku: 'TEC-LOGI-GPROX',
        images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500'],
        featured: false,
        brand: 'Logitech',
        warranty: '24 meses',
        specifications: {
          switches: 'GX Blue/Red/Brown intercambiables',
          iluminacion: 'RGB LIGHTSYNC por tecla',
          diseño: 'Tenkeyless',
          conectividad: 'USB',
        },
        slug: 'teclado-mecanico-logitech-g-pro-x',
        metaTitle: 'Teclado Mecánico Logitech G Pro X - Gaming',
        metaDescription: 'Teclado mecánico con switches intercambiables y RGB LIGHTSYNC.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Mouse Razer DeathAdder V3 Pro',
        description: 'Mouse inalámbrico gaming Razer DeathAdder V3 Pro con sensor Focus Pro 30K DPI, switches ópticas Gen-3, batería de 90 horas y diseño ergonómico.',
        category: 'ELECTRONICA',
        price: 699.90,
        stock: 35,
        sku: 'MOUSE-RAZER-DA-V3',
        images: ['https://images.unsplash.com/photo-1527814050087-3793815479db?w=500'],
        featured: false,
        brand: 'Razer',
        warranty: '24 meses',
        specifications: {
          sensor: 'Focus Pro 30K DPI',
          conectividad: 'Inalámbrico HyperSpeed',
          bateria: 'Hasta 90 horas',
          switches: 'Ópticas Gen-3',
          peso: '63g',
        },
        slug: 'mouse-razer-deathadder-v3-pro',
        metaTitle: 'Mouse Razer DeathAdder V3 Pro - Gaming',
        metaDescription: 'Mouse gaming inalámbrico con sensor 30K DPI y 90 horas de batería.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Tablet Samsung Galaxy Tab S9 11"',
        description: 'Tablet Samsung Galaxy Tab S9 con pantalla Dynamic AMOLED 2X de 11", procesador Snapdragon 8 Gen 2, 8GB RAM, 128GB almacenamiento, S Pen incluido.',
        category: 'ELECTRONICA',
        price: 2499.90,
        stock: 14,
        sku: 'TAB-SAMS-S9-11',
        images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500'],
        featured: false,
        brand: 'Samsung',
        warranty: '12 meses',
        specifications: {
          pantalla: '11" Dynamic AMOLED 2X 120Hz',
          procesador: 'Snapdragon 8 Gen 2',
          ram: '8GB',
          almacenamiento: '128GB',
          sPen: 'Incluido',
          bateria: '8400 mAh',
        },
        slug: 'tablet-samsung-galaxy-tab-s9-11',
        metaTitle: 'Tablet Samsung Galaxy Tab S9 11" con S Pen',
        metaDescription: 'Tablet Samsung con pantalla AMOLED 120Hz y S Pen incluido.',
      },
    }),
  ])
  console.log(`✅ ${electronicaProducts.length} productos de ELECTRÓNICA creados\n`)

  // PRODUCTOS - ALIMENTOS (10 productos)
  console.log('🍔 Creando productos de ALIMENTOS...')
  const alimentosProducts = await Promise.all([
    prisma.product.create({
      data: {
        name: 'Quinua Orgánica Andina Premium 1kg',
        description: 'Quinua orgánica certificada de los Andes peruanos. Rica en proteínas, fibra y minerales. Sin gluten. Ideal para dietas saludables.',
        category: 'ALIMENTOS',
        price: 24.90,
        stock: 100,
        sku: 'QUINUA-ORG-1KG',
        images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500'],
        featured: true,
        brand: 'Andean Harvest',
        slug: 'quinua-organica-andina-premium-1kg',
        metaTitle: 'Quinua Orgánica Andina Premium 1kg',
        metaDescription: 'Quinua orgánica peruana, rica en proteínas y sin gluten.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Aceite de Oliva Extra Virgen Borges 500ml',
        description: 'Aceite de oliva extra virgen español de primera extracción en frío. Acidez menor a 0.4%. Ideal para ensaladas y cocina mediterránea.',
        category: 'ALIMENTOS',
        price: 45.90,
        stock: 80,
        sku: 'ACEITE-BORGES-500',
        images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500'],
        featured: false,
        brand: 'Borges',
        slug: 'aceite-de-oliva-extra-virgen-borges-500ml',
        metaTitle: 'Aceite de Oliva Extra Virgen Borges 500ml',
        metaDescription: 'Aceite de oliva español de primera extracción en frío.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Miel de Abeja Pura 100% Natural 500g',
        description: 'Miel de abeja pura y natural sin procesar. Directamente del apicultor. Rica en antioxidantes y propiedades antibacterianas.',
        category: 'ALIMENTOS',
        price: 35.90,
        stock: 60,
        sku: 'MIEL-PURA-500G',
        images: ['https://images.unsplash.com/photo-1587049352846-4a222e784420?w=500'],
        featured: true,
        brand: 'Miel Andina',
        slug: 'miel-de-abeja-pura-100-natural-500g',
        metaTitle: 'Miel de Abeja Pura 100% Natural 500g',
        metaDescription: 'Miel pura sin procesar, rica en antioxidantes.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Café Orgánico Molido Tunki 250g',
        description: 'Café orgánico premium de Puno, Perú. Ganador de múltiples premios internacionales. Notas de chocolate y frutos secos.',
        category: 'ALIMENTOS',
        price: 39.90,
        stock: 75,
        sku: 'CAFE-TUNKI-250G',
        images: ['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=500'],
        featured: true,
        brand: 'Tunki',
        slug: 'cafe-organico-molido-tunki-250g',
        metaTitle: 'Café Orgánico Tunki 250g - Premium',
        metaDescription: 'Café peruano premiado con notas de chocolate.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Avena Integral Quaker Hojuelas 1kg',
        description: 'Avena integral en hojuelas, rica en fibra y proteínas. Perfecta para desayunos saludables. Sin azúcar añadida.',
        category: 'ALIMENTOS',
        price: 18.90,
        stock: 120,
        sku: 'AVENA-QUAKER-1KG',
        images: ['https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=500'],
        featured: false,
        brand: 'Quaker',
        slug: 'avena-integral-quaker-hojuelas-1kg',
        metaTitle: 'Avena Integral Quaker Hojuelas 1kg',
        metaDescription: 'Avena integral rica en fibra, sin azúcar añadida.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Pisco Quebranta Don Cesar 700ml',
        description: 'Pisco puro quebranta de uvas seleccionadas del valle de Ica. Destilación artesanal. Medalla de oro en concursos internacionales.',
        category: 'ALIMENTOS',
        price: 89.90,
        stock: 45,
        sku: 'PISCO-DCESAR-700',
        images: ['https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500'],
        featured: true,
        brand: 'Don Cesar',
        slug: 'pisco-quebranta-don-cesar-700ml',
        metaTitle: 'Pisco Quebranta Don Cesar 700ml',
        metaDescription: 'Pisco puro peruano de destilación artesanal.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Arroz Extra Costeño 5kg',
        description: 'Arroz extra de grano largo, rendidor y de cocción perfecta. Ideal para todo tipo de preparaciones.',
        category: 'ALIMENTOS',
        price: 27.90,
        stock: 90,
        sku: 'ARROZ-COST-5KG',
        images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500'],
        featured: false,
        brand: 'Costeño',
        slug: 'arroz-extra-costeno-5kg',
        metaTitle: 'Arroz Extra Costeño 5kg - Grano Largo',
        metaDescription: 'Arroz de grano largo, rendidor y de cocción perfecta.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Chocolate Bitter 70% Cacao Perú 100g',
        description: 'Chocolate bitter con 70% de cacao peruano. Sin azúcar refinada. Rico en antioxidantes. Sabor intenso y aromático.',
        category: 'ALIMENTOS',
        price: 22.90,
        stock: 85,
        sku: 'CHOCO-BIT-70-100',
        images: ['https://images.unsplash.com/photo-1511381939415-e44015466834?w=500'],
        featured: false,
        brand: 'Cacao Perú',
        slug: 'chocolate-bitter-70-cacao-peru-100g',
        metaTitle: 'Chocolate Bitter 70% Cacao Perú 100g',
        metaDescription: 'Chocolate peruano con 70% cacao, rico en antioxidantes.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Pasta Integral Don Vittorio Spaghetti 500g',
        description: 'Pasta italiana integral de sémola de trigo durum. Alta en fibra. Cocción al dente perfecta.',
        category: 'ALIMENTOS',
        price: 14.90,
        stock: 110,
        sku: 'PASTA-DVT-INT-500',
        images: ['https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500'],
        featured: false,
        brand: 'Don Vittorio',
        slug: 'pasta-integral-don-vittorio-spaghetti-500g',
        metaTitle: 'Pasta Integral Don Vittorio Spaghetti 500g',
        metaDescription: 'Pasta integral italiana de sémola de trigo durum.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Sal Rosa del Himalaya Fina 500g',
        description: 'Sal rosa del Himalaya sin refinar, rica en minerales (84 elementos). Sabor suave y delicado. Ideal para todo tipo de cocina.',
        category: 'ALIMENTOS',
        price: 28.90,
        stock: 70,
        sku: 'SAL-ROSA-HIM-500',
        images: ['https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=500'],
        featured: false,
        brand: 'Himalayan Salt',
        slug: 'sal-rosa-del-himalaya-fina-500g',
        metaTitle: 'Sal Rosa del Himalaya Fina 500g',
        metaDescription: 'Sal rosa sin refinar, rica en 84 minerales.',
      },
    }),
  ])
  console.log(`✅ ${alimentosProducts.length} productos de ALIMENTOS creados\n`)

  // PRODUCTOS - OTROS (10 productos)
  console.log('📦 Creando productos de OTROS...')
  const otrosProducts = await Promise.all([
    prisma.product.create({
      data: {
        name: 'Mochila North Face Borealis 28L',
        description: 'Mochila versátil con compartimento acolchado para laptop de 15", sistema FlexVent, múltiples bolsillos organizadores. Perfecta para trabajo y viajes.',
        category: 'OTROS',
        price: 389.90,
        stock: 25,
        sku: 'MOCHILA-TNF-BOR-28',
        images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500'],
        featured: true,
        brand: 'The North Face',
        colors: ['Negro', 'Azul', 'Gris'],
        slug: 'mochila-north-face-borealis-28l',
        metaTitle: 'Mochila North Face Borealis 28L',
        metaDescription: 'Mochila para laptop 15" con sistema FlexVent.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Botella Térmica Stanley 1L Classic',
        description: 'Botella térmica de acero inoxidable que mantiene líquidos calientes 24h y fríos 12h. Tapa con sistema anti-goteo. Prácticamente indestructible.',
        category: 'OTROS',
        price: 149.90,
        stock: 40,
        sku: 'BOTELLA-STN-1L',
        images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500'],
        featured: false,
        brand: 'Stanley',
        colors: ['Verde', 'Negro', 'Azul'],
        slug: 'botella-termica-stanley-1l-classic',
        metaTitle: 'Botella Térmica Stanley 1L Classic',
        metaDescription: 'Termo Stanley que mantiene temperatura 24 horas.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Set de Yoga Manduka 5 Piezas',
        description: 'Set completo de yoga: mat de 6mm antideslizante, 2 bloques de corcho, correa de algodón y bolsa de transporte. Todo lo que necesitas para tu práctica.',
        category: 'OTROS',
        price: 279.90,
        stock: 20,
        sku: 'YOGA-SET-MAND-5',
        images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500'],
        featured: true,
        brand: 'Manduka',
        colors: ['Morado', 'Verde', 'Azul'],
        slug: 'set-de-yoga-manduka-5-piezas',
        metaTitle: 'Set de Yoga Manduka 5 Piezas Completo',
        metaDescription: 'Set de yoga con mat, bloques, correa y bolsa.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Plancha de Pelo Remington Shine Therapy',
        description: 'Plancha profesional con placas de cerámica de turmalina, control digital de temperatura hasta 230°C, calentamiento en 30 segundos.',
        category: 'OTROS',
        price: 189.90,
        stock: 30,
        sku: 'PLANCHA-REM-SHINE',
        images: ['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=500'],
        featured: false,
        brand: 'Remington',
        slug: 'plancha-de-pelo-remington-shine-therapy',
        metaTitle: 'Plancha de Pelo Remington Shine Therapy',
        metaDescription: 'Plancha profesional con cerámica de turmalina.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Perfume Nautica Voyage EDT 100ml',
        description: 'Fragancia masculina fresca y acuática. Notas de manzana, loto acuático y ámbar. Perfecta para uso diario.',
        category: 'OTROS',
        price: 129.90,
        comparePrice: 169.90,
        stock: 45,
        sku: 'PERF-NAUT-VOY-100',
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=500'],
        featured: false,
        brand: 'Nautica',
        slug: 'perfume-nautica-voyage-edt-100ml',
        metaTitle: 'Perfume Nautica Voyage EDT 100ml',
        metaDescription: 'Fragancia masculina fresca y acuática.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Carpa Coleman Sundome 4 Personas',
        description: 'Carpa familiar para 4 personas con sistema WeatherTec resistente al agua, ventilación superior, instalación en 10 minutos.',
        category: 'OTROS',
        price: 449.90,
        stock: 15,
        sku: 'CARPA-COLE-SD4',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=500'],
        featured: true,
        brand: 'Coleman',
        slug: 'carpa-coleman-sundome-4-personas',
        metaTitle: 'Carpa Coleman Sundome 4 Personas',
        metaDescription: 'Carpa impermeable para 4 personas, fácil instalación.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Lentes de Sol Ray-Ban Aviator Clásico',
        description: 'Lentes de sol icónicos Ray-Ban Aviator con lentes polarizadas, protección UV400, montura de metal dorado.',
        category: 'OTROS',
        price: 459.90,
        stock: 35,
        sku: 'LENTES-RB-AVI-CLS',
        images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500'],
        featured: false,
        brand: 'Ray-Ban',
        colors: ['Dorado/Verde', 'Dorado/Marrón', 'Plata/Gris'],
        slug: 'lentes-de-sol-ray-ban-aviator-clasico',
        metaTitle: 'Lentes Ray-Ban Aviator Clásico Polarizados',
        metaDescription: 'Lentes Ray-Ban Aviator con protección UV400.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Balón Nike Strike Premier League',
        description: 'Balón oficial de la Premier League, tecnología Nike Aerowsculpt, diseño gráfico de alto contraste para mejor visibilidad.',
        category: 'OTROS',
        price: 149.90,
        stock: 50,
        sku: 'BALON-NIKE-EPL',
        images: ['https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aac?w=500'],
        featured: false,
        brand: 'Nike',
        sizes: ['5'],
        slug: 'balon-nike-strike-premier-league',
        metaTitle: 'Balón Nike Strike Premier League Oficial',
        metaDescription: 'Balón oficial Premier League con tecnología Aerowsculpt.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Colchoneta de Camping Decathlon Forclaz',
        description: 'Colchoneta inflable ultraligera con sistema de inflado integrado. Peso 650g, grosor 7cm. Perfecta para trekking.',
        category: 'OTROS',
        price: 199.90,
        stock: 28,
        sku: 'COLCH-DECA-FORC',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500'],
        featured: false,
        brand: 'Decathlon',
        colors: ['Azul', 'Verde'],
        slug: 'colchoneta-de-camping-decathlon-forclaz',
        metaTitle: 'Colchoneta Camping Decathlon Forclaz Inflable',
        metaDescription: 'Colchoneta ultraligera 650g, grosor 7cm.',
      },
    }),
    prisma.product.create({
      data: {
        name: 'Juego de Sábanas Pima Cotton 300 Hilos Queen',
        description: 'Juego de sábanas de algodón Pima peruano 300 hilos. Incluye sábana, funda de edredón y 2 fundas de almohada. Suavidad premium.',
        category: 'OTROS',
        price: 289.90,
        stock: 22,
        sku: 'SABANAS-PIMA-Q-300',
        images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500'],
        featured: true,
        brand: 'Pima Cotton',
        colors: ['Blanco', 'Gris', 'Azul Marino'],
        sizes: ['Queen'],
        slug: 'juego-de-sabanas-pima-cotton-300-hilos-queen',
        metaTitle: 'Sábanas Pima Cotton 300 Hilos Queen',
        metaDescription: 'Sábanas de algodón Pima peruano, suavidad premium.',
      },
    }),
  ])
  console.log(`✅ ${otrosProducts.length} productos de OTROS creados\n`)

  // Crear órdenes de demostración
  console.log('🛒 Creando órdenes de demostración...')
  
  const order1 = await prisma.order.create({
    data: {
      orderNumber: 'ORD-2024-00001',
      userId: users[1].id,
      customerName: users[1].name!,
      customerEmail: users[1].email,
      customerPhone: users[1].phone!,
      customerDni: users[1].dni!,
      customerAddress: users[1].address!,
      subtotal: 419.80,
      tax: 75.56,
      total: 495.36,
      paymentMethod: 'CULQI',
      paymentStatus: 'COMPLETED',
      status: 'DELIVERED',
      paidAt: new Date('2024-11-10T10:30:00'),
      deliveredAt: new Date('2024-11-12T15:45:00'),
      items: {
        create: [
          {
            productId: ropaProducts[0].id,
            productName: ropaProducts[0].name,
            price: ropaProducts[0].price,
            quantity: 2,
            size: 'L',
            color: 'Azul',
            sku: ropaProducts[0].sku,
            imageUrl: ropaProducts[0].images[0],
          },
          {
            productId: ropaProducts[3].id,
            productName: ropaProducts[3].name,
            price: ropaProducts[3].price,
            quantity: 1,
            size: '42',
            color: 'Negro',
            sku: ropaProducts[3].sku,
            imageUrl: ropaProducts[3].images[0],
          },
        ],
      },
    },
  })

  const order2 = await prisma.order.create({
    data: {
      orderNumber: 'ORD-2024-00002',
      userId: users[2].id,
      customerName: users[2].name!,
      customerEmail: users[2].email,
      customerPhone: users[2].phone!,
      customerDni: users[2].dni!,
      customerAddress: users[2].address!,
      subtotal: 7398.80,
      tax: 1331.78,
      total: 8730.58,
      paymentMethod: 'NIUBIZ',
      paymentStatus: 'COMPLETED',
      status: 'SHIPPED',
      paidAt: new Date('2024-11-11T14:20:00'),
      shippedAt: new Date('2024-11-12T09:00:00'),
      items: {
        create: [
          {
            productId: electronicaProducts[0].id,
            productName: electronicaProducts[0].name,
            price: electronicaProducts[0].price,
            quantity: 1,
            sku: electronicaProducts[0].sku,
            imageUrl: electronicaProducts[0].images[0],
          },
          {
            productId: electronicaProducts[3].id,
            productName: electronicaProducts[3].name,
            price: electronicaProducts[3].price,
            quantity: 2,
            sku: electronicaProducts[3].sku,
            imageUrl: electronicaProducts[3].images[0],
          },
          {
            productId: electronicaProducts[4].id,
            productName: electronicaProducts[4].name,
            price: electronicaProducts[4].price,
            quantity: 1,
            sku: electronicaProducts[4].sku,
            imageUrl: electronicaProducts[4].images[0],
          },
        ],
      },
    },
  })

  const order3 = await prisma.order.create({
    data: {
      orderNumber: 'ORD-2024-00003',
      userId: users[3].id,
      customerName: users[3].businessName!,
      customerEmail: users[3].email,
      customerPhone: users[3].phone!,
      customerRuc: users[3].ruc!,
      customerAddress: users[3].address!,
      subtotal: 188.90,
      tax: 34.00,
      total: 222.90,
      paymentMethod: 'YAPE',
      paymentStatus: 'COMPLETED',
      status: 'PROCESSING',
      paidAt: new Date('2024-11-12T16:45:00'),
      items: {
        create: [
          {
            productId: alimentosProducts[0].id,
            productName: alimentosProducts[0].name,
            price: alimentosProducts[0].price,
            quantity: 3,
            sku: alimentosProducts[0].sku,
            imageUrl: alimentosProducts[0].images[0],
          },
          {
            productId: alimentosProducts[2].id,
            productName: alimentosProducts[2].name,
            price: alimentosProducts[2].price,
            quantity: 2,
            sku: alimentosProducts[2].sku,
            imageUrl: alimentosProducts[2].images[0],
          },
          {
            productId: alimentosProducts[3].id,
            productName: alimentosProducts[3].name,
            price: alimentosProducts[3].price,
            quantity: 2,
            sku: alimentosProducts[3].sku,
            imageUrl: alimentosProducts[3].images[0],
          },
        ],
      },
    },
  })

  console.log(`✅ 3 órdenes creadas\n`)

  // Crear facturas de demostración
  console.log('🧾 Creando comprobantes SUNAT de demostración...')
  
  await prisma.invoice.create({
    data: {
      orderId: order1.id,
      documentType: '3',
      series: 'B001',
      number: 1,
      fullNumber: 'B001-00000001',
      issuerRuc: process.env.COMPANY_RUC || '20123456789',
      issuerName: process.env.COMPANY_NAME || 'Mi Empresa SAC',
      issuerAddress: process.env.COMPANY_ADDRESS || 'Jr. Example 123, Lima',
      customerType: '1',
      customerDocNumber: order1.customerDni!,
      customerName: order1.customerName,
      customerAddress: order1.customerAddress,
      subtotal: order1.subtotal,
      igv: order1.tax,
      total: order1.total,
      sunatStatus: 'ACEPTADO',
      sunatResponse: {
        acceptance_status: 'ACCEPTED',
        sunat_responsecode: '0',
        sunat_description: 'La Boleta numero B001-00000001, ha sido aceptada',
      },
      qrCode: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=20123456789|B001|00000001|495.36',
      hash: 'dGVzdC1oYXNoLTEyMzQ1LWFiY2RlZi1naGlqa2xtbm8=',
      sentToSunatAt: new Date('2024-11-10T10:32:00'),
    },
  })

  await prisma.invoice.create({
    data: {
      orderId: order3.id,
      documentType: '1',
      series: 'F001',
      number: 1,
      fullNumber: 'F001-00000001',
      issuerRuc: process.env.COMPANY_RUC || '20123456789',
      issuerName: process.env.COMPANY_NAME || 'Mi Empresa SAC',
      issuerAddress: process.env.COMPANY_ADDRESS || 'Jr. Example 123, Lima',
      customerType: '6',
      customerDocNumber: order3.customerRuc!,
      customerName: order3.customerName,
      customerAddress: order3.customerAddress,
      subtotal: order3.subtotal,
      igv: order3.tax,
      total: order3.total,
      sunatStatus: 'ACEPTADO',
      sunatResponse: {
        acceptance_status: 'ACCEPTED',
        sunat_responsecode: '0',
        sunat_description: 'La Factura numero F001-00000001, ha sido aceptada',
      },
      qrCode: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=20123456789|F001|00000001|222.90',
      hash: 'dGVzdC1oYXNoLTY3ODkwLXBxcnN0dXZ3eHl6LWFiY2RlZg==',
      sentToSunatAt: new Date('2024-11-12T16:48:00'),
    },
  })

  console.log(`✅ 2 comprobantes SUNAT creados\n`)

  console.log('🎉 ¡Seed completado exitosamente!')
  console.log('\n📊 RESUMEN:')
  console.log(`   👥 Usuarios: ${users.length}`)
  console.log(`   📦 Productos: ${ropaProducts.length + electronicaProducts.length + alimentosProducts.length + otrosProducts.length}`)
  console.log(`      - Ropa: ${ropaProducts.length}`)
  console.log(`      - Electrónica: ${electronicaProducts.length}`)
  console.log(`      - Alimentos: ${alimentosProducts.length}`)
  console.log(`      - Otros: ${otrosProducts.length}`)
  console.log(`   🛒 Órdenes: 3`)
  console.log(`   🧾 Comprobantes: 2`)
  console.log('\n✅ Tu demo está lista para presentar!\n')
}

main()
  .catch((e) => {
    console.error('❌ Error durante el seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

